2023-03-13 20:43:03 [INFO] persisted: Persisted(last_successful_crawls={'ffmpeg': '2023-03-13 20:33:26.542983+00:00', 'golang-defaults': '2023-03-13 20:33:25.620285+00:00', 'python3-defaults': '2023-03-13 20:33:24.965135+00:00', 'rustc': '2023-03-13 20:33:24.984407+00:00', 'zsh': '2023-03-13 20:33:25.446196+00:00'})
2023-03-13 20:43:03 [INFO] config: Config(feed=FeedConfig(base_url='https://release-feeds.zhimingwang.org/', author='release-feeds', aggregate_title='Aggregate software releases'), packages=['ffmpeg', 'golang-defaults', 'python3-defaults', 'rustc', 'zsh'])
2023-03-13 20:43:03 [INFO] GET https://sources.debian.org/api/src/ffmpeg/
2023-03-13 20:43:03 [INFO] GET https://sources.debian.org/api/src/python3-defaults/
2023-03-13 20:43:03 [INFO] GET https://sources.debian.org/api/src/rustc/
2023-03-13 20:43:03 [INFO] GET https://sources.debian.org/api/src/zsh/
2023-03-13 20:43:03 [ERROR] failed to update entry for zsh
Traceback (most recent call last):
  File "src/update.py", line 354, in try_updating_registry_entry
    entry = try_updating_entry(package, existing_entry=existing_entry)
  File "src/update.py", line 319, in try_updating_entry
    latest_version = get_package_version(package)
  File "src/update.py", line 310, in get_package_version
    acquire_watch_file(package, debian_dir)
  File "src/update.py", line 276, in acquire_watch_file
    download_watch_file(package, destdir)
  File "/home/runner/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/home/runner/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/home/runner/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/runner/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "src/update.py", line 242, in download_watch_file
    raise RuntimeError(f"GET {url}: {r.text}")
RuntimeError: GET https://sources.debian.org/api/src/zsh/: {"error":404}

2023-03-13 20:43:03 [INFO] GET https://sources.debian.org/api/src/ffmpeg/7:5.1.2-3/debian/watch
2023-03-13 20:43:03 [INFO] GET https://sources.debian.org/api/src/rustc/1.63.0+dfsg1-2/debian/watch
2023-03-13 20:43:03 [INFO] GET https://sources.debian.org/api/src/python3-defaults/3.11.2-1/debian/watch
2023-03-13 20:43:03 [INFO] GET https://sources.debian.org/data/main/r/rustc/1.63.0%2Bdfsg1-2/debian/watch
2023-03-13 20:43:03 [INFO] GET https://sources.debian.org/data/main/p/python3-defaults/3.11.2-1/debian/watch
2023-03-13 20:43:03 [INFO] GET https://sources.debian.org/data/main/f/ffmpeg/7%3A5.1.2-3/debian/watch
2023-03-13 20:43:04 [INFO] rustc 1.68.0: https://static.rust-lang.org/dist/rustc-1.68.0-src.tar.xz
2023-03-13 20:43:04 [INFO] python3-defaults 3.11.2: https://www.python.org/ftp/python/3.11.2/Python-3.11.2.tar.xz
2023-03-13 20:43:05 [INFO] golang-defaults 1.20.2: https://golang.org/dl/go1.20.2.src.tar.gz
2023-03-13 20:43:05 [INFO] ffmpeg 6.0: https://ffmpeg.org/releases/ffmpeg-6.0.tar.xz
2023-03-13 20:43:05 [INFO] no updates found
2023-03-13 20:43:05 [ERROR] failed: zsh
